In [1]:
import os
import pandas as pd
from sklearn.model_selection import train_test_split
from imutils import paths

In [3]:
os.getcwd()
os.chdir('vgg_16_approach/')

In [5]:
import config

In [6]:
config.base_path

'/home/safat/python_code/emergency_vehicle_detection/vgg_16_approach'

In [7]:
cars = pd.read_csv(os.path.join(config.images_path,'train_test_vgg_format.csv'))

In [17]:
data = [] #images
labels = []
bboxes = []
filenames = []


In [18]:
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing.image import load_img
for i in cars.IMAGE:
    image = load_img(os.path.join(config.images_path,'cars', str(i) + ".jpg"))
    image = img_to_array(image)
    
    data.append(image)

In [20]:
tmp = []
for i in range(len(cars)):
	for j in range(1,5):
		tmp.append(cars.iloc[i,j])
		
	labels.append(cars.CLASS[i])
	bboxes.append(tmp)
	tmp = []

In [24]:
print(len(labels))
print(len(data))
print(bboxes[0])
print(len(bboxes))

2321
2321
[0.08705357142857142, 0.125, 0.9308035714285714, 0.8660714285714286]
2321


In [43]:
import numpy as np
# convert the data and labels to NumPy arrays, scaling the input
# pixel intensities from the range [0, 255] to [0, 1]
data = np.array(data, dtype="float32") / 255.0
labels = np.array(labels, dtype="float32")
bboxes = np.array(bboxes)


In [39]:
split = train_test_split(data, labels, bboxes, test_size=0.10,
	random_state=42)

In [40]:
len(split)

6

In [41]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
labels = lb.fit_transform(labels)

In [44]:
labels

array([[1.],
       [1.],
       [1.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

In [46]:
from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels)

In [47]:
labels

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [48]:
labels[0]

array([0., 1.], dtype=float32)